import {faker} from "@faker-js/faker/locale/vi";
import {ButtonGroup} from "@/components/ui/button-group.tsx";
import {Input} from "@/components/ui/input.tsx";
import {Button} from "@/components/table/button.tsx";
import {useState} from "react";
import * as XLSX from "xlsx";

type Equipment = {
    cp_nm: string,
    lct_nm: string,
    mf_nm: string,
    md_nm: string,
    mt_cd: string,
    mt_nm: string,
    sp_nm: string,
    cost_dept_nm: string,
    lct_sts_nm: string,
    mgm_dept_nm: string,
    print_yn: string,
    use_yn: string,
    as_no: number,
    as_sno: number,
    srl_no: number,
    re_mark: string,
    dev_start_dt: Date,
    puchs_dt: Date,
    vailed_dt: Date,
}


const makeEquipments = (num: number) => {
    const equipments: Equipment[] = [];
    const today = new Date();
    for (let i = 0; i < num; i++) {

        const startDate = faker.date.between({from: '2020/11/03', to: '2022/01/02'});
        const validDate = faker.date.between({from: '2024/01/01', to: today})
        const punchDate = faker.date.between({from: startDate, to: validDate})

        equipments.push({
            cp_nm: 'HSV',
            lct_nm: faker.helpers.arrayElement([
                "1FAC",
                "2FAC",
                "3FAC",
                "LONG THANH",
                "VUNG TAU",
                "O/S PRESS",
                "IBS",
                "DIRECT SOLING",
                "INHOUSE",
                "CKD",
                "IP",
                "COMPOUND",
                "QSM W/H",
                "DEV ADIDAS",
                "DEV PERFORMANCE",
                "CHANG CHUN",
                "RACH GIA",
                "MAIN W/H",
                "ACE WORLD",
                "BUWON",
                "CHEONG AM",
                "CHUNIL",
                "EZ SPORTS",
                "GIAI HOP",
                "HS POLYTECH",
                "JIA HUE",
                "JOOCO DONA",
                "KOVA",
                "MOA",
                "P & F",
                "PHOSPIN",
                "TEASUNG",
                "SUNG MO",
                "RACHGIA AS SET",
                "CHANG CHUN ST",
                "HSM",
                "TRACK VINA",
                "UNIPAX",
                "CHOONGNAM VN",
                "TOAN LOC",
                "DONG HUNG",
                "KIM BAO THINH",
                "NGUYEN THANH HUNG",
                "DONG SHIN",
                "FUTURE",
                "SOC TRANG",
                "RG FAC A",
                "RG FAC B",
                "RG FAC C",
                "RG FAC D",
                "RG FAC E",
                "RG INHOUSE",
                "JOO WON",
                "TSRG",
                "STECH",
                "DAE YOUNG TEXTILE",
                "MATERIAL WAREHOUSE",
                "SYN,TX,SUB W/H",
                "Main Storage W/H",
                "4D W/H",
                "FAC.1 Asmbly Set",
                "FAC.1 Cutt. Set",
                "FAC.1 Cut&Part",
                "Packing W/H F1",
                "F1 Innerbox W/H",
                "FAC.1 IMTF W/H",
                "BACK LOG WH 01",
                "Packing W/H",
                "LEATHER W/H(WMS)",
                "FAC.2 Asmbly Set",
                "FAC.2 Cutt. Set",
                "FAC.2 Cut&Part",
                "Packing W/H F2",
                "F2 Innerbox W/H",
                "FAC.2 IMTF W/H",
                "BACK LOG WH 02",
                "Consumption W/H",
                "FAC.3 Asmbly Set",
                "FAC.3 Cutt. Set",
                "FAC.3 Cut&Part",
                "Packing W/H F3",
                "F3 Innerbox W/H",
                "FAC.3 IMTF W/H",
                "FAC.3 DUMMY",
                "Loss Mat. W/H",
                "FAC.5 Asmbly Set",
                "FAC.5 Cutt. Set",
                "IMEVA W/H",
                "Packing W/H F5",
                "F5 Innerbox W/H",
                "FAC.5 IMTF W/H",
                "POLO Mat. S/LOC",
                "Main Chemical WH",
                "Bond DN W/H",
                "Bond RG W/H",
                "Bond ST W/H",
                "OSC Compound W/H",
                "Engin. Sole SET",
                "Enginneer Part",
                "OS Chemical",
                "CMEVA Chemical",
                "DC EVA Chemical",
                "PU Insole Chemic",
                "ADH_RAW MAT",
                "ADH_PACKING",
                "MIX_ADHENSIVE",
                "ADH_COMPOUND",
                "FG_A401",
                "FG_A403",
                "ADH_RETURN",
                "F.LT Mat. W/H",
                "F.LT UP00 Stock",
                "F.LT Cutt. Set",
                "F.LT Cut&Part",
                "HVC Compound W/H",
                "F.VT Asmbly Set",
                "F.VT Cutt. Set",
                "F.VT Cut&Part",
                "Ecomelt ROH",
                "Ecomelt HALB",
                "F.VT FinishW/H",
                "Ecomelt Backlog",
                "Development W/H",
                "F.Ds S.FG W/H",
                "F.Ds Raw W/H",
                "F.Ds Finish W/H",
                "B-GRADE W/H",
                "CHANG CHUN CT",
                "RG.FC Innerbox",
                "RG.FD Asmbly Set",
                "RG.FD Cutt. Set",
                "RG.FD Cut&Part",
                "CHANG CHUN MAT.",
                "RG.FC Asmbly Set",
                "RG.FC Cutt. Set",
                "RG.FC Cut&Part",
                "W/H C/Y",
                "F1 Carton W/H",
                "F2 Carton W/H",
                "F3 Carton W/H",
                "F5 Carton WH",
                "RG Carton W/H",
                "ACE WORLD CT",
                "SUNG HYUN CT",
                "DKS CT",
                "P & F CT",
                "NOVA CT",
                "ACE WORLD ST",
                "SUNG HYUN ST",
                "DKS ST",
                "P & F ST",
                "NOVA ST",
                "RG.FA Innerbox",
                "JOOCO AS",
                "JOOCO ST",
                "JOOCO CT",
                "SAMIL ST",
                "SAMIL CT",
                "SIGNAL ST",
                "SIGNAL CT",
                "CHUN IL ST",
                "CHUN IL CT",
                "YOUNG IN ST",
                "YOUNG IN CT",
                "TV AS Setting",
                "TV CT Setting",
                "KHT UP Setting",
                "KHT CT Setting",
                "RG.FA Asmbly Set",
                "RG.FA Cut&Part",
                "Toan Loc Ass Set",
                "TOAN LOC ST",
                "TOAN LOC CT",
                "TBS Innerbox",
                "TBS AS Setting",
                "TBS CT Setting",
                "TBS CT Part&Raw",
                "DH Innerbox",
                "DH AS Setting",
                "DH CT Setting",
                "DH CT Part&Raw",
                "RG.FB Innerbox",
                "RG.FB Asmbly Set",
                "RG.FB Cutt. Set",
                "RG.FB Cut&Part",
                "Long Term Stock",
                "PLANT 1(FACTORY",
                "Main warehouse",
                "MCS room",
                "Tech warehouse",
                "Keep sample room",
                "Keep sample room",
                "Adidas OCPT",
                "PDM Keeping Room",
                "Inspection Room",
                "BOM Keeping Room",
                "Sample Main W/H",
                "Inspection Room",
                "Sample room",
                "PLANT 2(FACTORY",
                "PLANT 3(FACTORY",
                "HWD",
                "CKD FACTORY",
                "TECH PLANT",
                "Development W/H",
                "FAC.DS W/H",
                "Scrap",
                "MAINTENANCE",
                "Eco Melt ROH",
                "Eco Melt HALB",
                "E.Melt Backflush",
                "RESTAURANT",
                "FACTORY 1",
                "FACTORY 2",
                "FACTORY 3",
                "FACTORY 5",
                "DORMITORY",
                "WAREHOUSE",
                "PRESS",
                "CHANG CHUN LONG",
                "IM EVA",
                "HWI",
                "GUARDHOUSE",
                "VACANT 1 & EXCEP",
                "VACANT 2 & EXCEP",
                "LAST WAREHOUSE",
                "LAST DESTROY",
                "LAB",
                "LONG THANH FACTO",
                "ROAD & EXCEPT",
                "MAINTENANCE OFFI",
                "MAINTENANCE WARE",
                "Nhat Phuong ST",
                "Nhat Phuong CT",
                "OUTSIDE",
                "Overrun Fac 1",
                "Overrun Fac 2",
                "Overrun Fac 3",
                "Overrun Fac 5",
                "Overrun Fac DS",
                "Overrun Fac RG",
                "RG W/H MAT",
                "RG W/H Packing",
                "Packing W/H RGFA",
                "Packing W/H RGFB",
                "Packing W/H RGFC",
                "RG FAC IMTF W/H",
                "Kids",
                "Tech room 1",
                "Tech room 2",
                "Training Room",
                "Innovation",
                "100",
                "200",
                "Lifestyle",
                "Running room",
                "Reebok OCPT",
                "LONG THANH",
                "FAC.VT",
                "VUNG TAU FACTORY",
                "AIR",
                "ELECTRIC"
            ]),
            mf_nm: faker.helpers.arrayElement([
                "A CHAU",
                "AHI GROUP",
                "ALLIANCES",
                "AMETEK",
                "ANAM",
                "ANZANI",
                "ATLAS",
                "ATOM",
                "AUBO",
                "BAOLI",
                "BLACK KING KONG",
                "BOA",
                "BONGSHIN",
                "BOYAN",
                "BRAVO TECH",
                "BROTHER",
                "BUMYANG",
                "C-SUN",
                "C.T.M",
                "CABALLO",
                "CARNO",
                "CASUN",
                "CHAINE",
                "CHANG YIH",
                "CHEE SIANG",
                "CHENFENG",
                "CHENFULL",
                "CHUAN NENG",
                "CHUANLI",
                "CLARK",
                "COMELZ.S.p.A",
                "COSMIG",
                "CUONG THINH",
                "DAESUNG",
                "DAI HAN",
                "DAILAN HUAHAN",
                "DAYU",
                "DEASUNG",
                "DEAWON",
                "DESMA",
                "DM TECH",
                "DONG HWA",
                "DONGGUAN",
                "Dongguan HCM",
                "DONGHWA",
                "DONGSEO(SINWOO TECH)",
                "DOOSAN",
                "EASEMENT",
                "EILY",
                "ELECTROLUX",
                "EMMA",
                "ENMO",
                "EXCON PART",
                "FIBLON",
                "FILBON",
                "FLY SCREW",
                "FUSEN",
                "FUSHENG (SUNGHWA)",
                "FUTONG",
                "FUZHOU SANJU",
                "GAOSHEN",
                "GD",
                "GO-TECH",
                "GOLDEN WHEEL",
                "GONGYUNG",
                "GOTECH",
                "GTM-KOREA",
                "GUANG YIN",
                "HAILI",
                "HANA",
                "HANIL",
                "HANJIN",
                "HANSHIN",
                "HANSHIN (FUSHENG)",
                "HARDO",
                "HARISON",
                "HEESUNG ENG",
                "HELI",
                "HONGXIANG",
                "HONGXIN",
                "HS-VINA",
                "HUACHENG",
                "HUASEN",
                "HUYNDAI",
                "HWANG SUN",
                "HWASEUNG DAILAN",
                "HYEKWANG",
                "IDICO",
                "IN YE",
                "INYE",
                "JANGCHUN",
                "JDB(JingDeBao)",
                "JIAJING",
                "JIAMA",
                "JIAN KWANG",
                "JIANHONG",
                "JIESHENG",
                "JING TAI",
                "JING YI",
                "JINGJY",
                "JINGMA",
                "JINGTAI",
                "JINGYI",
                "JINMA",
                "JINWANG",
                "JINYINFENG",
                "JIYUAN",
                "JUKI",
                "JUYUAN",
                "JUYUAN(HAILI)",
                "JWELL",
                "KANGYIDA",
                "KDS",
                "KEXIM",
                "KING AIR",
                "KING LEN",
                "KING STEEL",
                "KINGLEN(JINJIANG)",
                "KINGSTEEL",
                "KOREA TECHNO",
                "KOREAENGERY SYSTEM",
                "KTC",
                "KUKDONG",
                "KUKDONG(VN)",
                "KY THUAT VINA",
                "LAN BO WANG",
                "LEADING",
                "LG",
                "LIANG CHI",
                "LICHENG",
                "LINX",
                "LONGWIN",
                "LUEN CHEONG",
                "LUXIN",
                "MAINRISE",
                "MANNUNG",
                "MANUNG",
                "MAV",
                "MAY CAT RAP GIAY ZUND S3M800",
                "MAY CAT RAP KHUON-MODEL:ZUND S",
                "MGA",
                "MIMA",
                "MIMAKI",
                "MINGSHEN",
                "MONTI ANTONIO",
                "MORGAN",
                "N.THAI BINH DUONG",
                "NAMSUNG",
                "NAVITAS VN",
                "NN",
                "NORDSON",
                "OHAUS - USA",
                "OLYMPIC",
                "OPTIM",
                "ORISOL",
                "PEGASUS",
                "PFAFF",
                "PINE CREATION ENTERPRISE",
                "PINGLIAN",
                "Power-Rise",
                "Precision",
                "PROSHOETECH",
                "PUMMA",
                "QINGDAO",
                "QUAN TAI",
                "Quangzhou Sunrise",
                "QUEENSENSE",
                "QUZHOU TAIWEI",
                "RAMPF",
                "ROBOT S.R.L.",
                "ROC",
                "ROTAL",
                "RUIAN JINGUANG",
                "RUIAN XIANGYUN",
                "SAGITTA",
                "SAMJEONG",
                "SANGHEE",
                "SANYO",
                "SCHOEN AND SANDT",
                "SEHUNG",
                "SEOJIN",
                "SEWQ",
                "SHANG JAN",
                "SHANGHAI EAST BEST",
                "SHANGHAI EASTBEST",
                "SHANGHAI LIZHU",
                "SHENGDA",
                "SHENZHEN AURORA",
                "SHIM CHEN",
                "SHIM YEEH",
                "SHINHAN",
                "SINH THINH",
                "SIRUBA",
                "SULIALR",
                "SULLAIR",
                "SUN TECH",
                "SUNG HWA",
                "SUNGHWA",
                "SUNGHWA VN",
                "SUNRISE",
                "SUNRISE FLUID POWER",
                "SUNSTAR",
                "SUNTAR",
                "SUNTECH",
                "SUPREME",
                "T.A.O",
                "TAIWAN",
                "TAM MINH QUAN",
                "TCM-SANYO",
                "TEAWOO",
                "TEN SHEEG",
                "TENYULONG",
                "TENZENG",
                "TESCO",
                "THIEN LOC PHAT",
                "THINH THIEN HAI",
                "THINHTHIENHAI",
                "THUONG THUY",
                "TIANCHANG",
                "TIEN KANG",
                "TIENKANG",
                "TUNG SHENG",
                "TY",
                "TYL_GERMANY KING INTERNATIONAL",
                "U-CAN DYNATEX",
                "UNICORN",
                "UNION",
                "USM",
                "USM-YANGCHENG",
                "USMC",
                "VILC",
                "VINA-TECHNO",
                "Weinmann",
                "WEIPENG",
                "WENZHOU N&A FOREIGN TRAD",
                "WINWING",
                "Wuxi Chaohong",
                "X-Rite",
                "XIANG YUN",
                "XINRUI",
                "XUAN HIEP PHAT",
                "XUNDE",
                "YANBAI",
                "YANCHENG HUASEN",
                "YE HONE",
                "YEUMING",
                "YOOSUNG",
                "YOU IL",
                "YUEMING",
                "ZEDAL",
                "ZHANG JIANG",
                "ZHANYANG",
                "ZHONG MING"
            ]),
            md_nm: faker.helpers.arrayElement([
                "ST-957B",
                "KM-957-7",
                "LT5-H7600-1",
                "KM-1957-7",
                "KM-957",
                "KM-76",
                "ST-77",
                "FS-3811",
                "KI-3811",
                "CN-600-20",
                "FS-600",
                "KM-967-7",
                "DB2-H311",
                "DPS-3",
                "JY-208",
                "DS-HUT500",
                "HS-0752",
                "ST-1310HS",
                "ST-1010HS",
                "ST-3020HS",
                "ST-6040HS",
                "CS-335",
                "CS-335L-BH",
                "ST-2210HS",
                "SPS/F-6040HS",
                "ST-380BL-B",
                "KM-380BL-B",
                "CS-335BS",
                "SGY2-2010-H-A-2",
                "ST-1510HS",
                "SPS/S-2516-HS-2",
                "SGY2-3020-H-B-2",
                "SPS/F-3020",
                "CSA-1510XY/HAD",
                "ST-2210HS-30",
                "DPK-3",
                "KD-105",
                "CSA-4830D-3-156",
                "CSA-4830-3-156M",
                "ST-7500ML-3S",
                "MS-268-L",
                "CSA-1300D-4-160",
                "HX-727E",
                "SPS/F-1310HS-10",
                "KD-107",
                "DS-201B",
                "ST-430D",
                "SPS/F-1310HS-20",
                "KM-235B",
                "LT5-H7200-1",
                "LT5-H7200-2",
                "SPS/A-2516HS-20",
                "SPS/A-1306HS-10",
                "ST-2210HS-50",
                "CS-1504-3-156M",
                "CS-1500-3-156M",
                "ST-8500M-3",
                "HS-1104-P2",
                "JT-104-P2",
                "DS-FD-203",
                "SS-109",
                "HX-141",
                "ST-2520B",
                "DS-NST-100",
                "DS-201A",
                "EH-929",
                "GF-250A",
                "KS-HR300",
                "SPS/B-2516HS-20",
                "SPS/A-5030-HS",
                "CS-1500-4-160M",
                "SPS/S-3050H",
                "ST-1310-3D",
                "SPS/C-5050HS",
                "SPS/E-5050H",
                "SPS/B-1507-HS-2",
                "ST-3020HS(3TB)",
                "ST-3020HS(4TT)",
                "SPS/F-2516HS-20",
                "SPS/E-1507HJ-23",
                "SPS/B-1507HS-10",
                "SPS/B-1306HS-10",
                "UAS-H1407",
                "KM-250B-7",
                "KM-740",
                "LT2-H620M",
                "CS-2604-02(S33-",
                "KM-867-7",
                "ST-867-7",
                "PLN-7B",
                "LX-215",
                "KM-867",
                "ST-1452/3",
                "PLN-27B",
                "ST-957B-7",
                "KD-105A",
                "747F",
                "ST-6800D-3",
                "CS-2390",
                "DPK-5",
                "CSM-3020GB-03A",
                "CR-3020",
                "KM-857-7",
                "LT5-H7600-2",
                "KM-967",
                "ST-967B",
                "AMS210ENHL2210",
                "KA-101",
                "LS2-H5100H",
                "LS2-H5150HUK",
                "ST-1530L",
                "ST-1530L-DZ",
                "JY-747",
                "FS-168A",
                "CS-2180",
                "ST-1530",
                "KM-137",
                "CSM-3020GB-01A",
                "ST-3020HS-P",
                "ST-3525HS-P",
                "TY-747",
                "ST-967B-7",
                "ST-2972",
                "TZ1-B652",
                "ST-2150M",
                "KM-957SR",
                "CSA-3020XY/HAF",
                "CSM-3020H-01A",
                "AMS210ENSS1306S",
                "CS-8713V",
                "DS-NST-100D",
                "KM-2520B",
                "M752-01",
                "M652-01-4",
                "AMS210ENHL2210/",
                "CSM-3020GB-01A/",
                "KD2002H",
                "SPS/E-1507HS-10",
                "ST-957SRB",
                "LX-203",
                "KD-H9",
                "DS-HMT",
                "SD-2030C",
                "TURBO FOST 2",
                "TF-2",
                "DS-HLT",
                "JY-501 (AUTO)",
                "SD-957",
                "SD-957-3CHAMBER",
                "SD-957-2CHAMBER",
                "C1200DA",
                "C1200DA-S",
                "SD-957-IC",
                "KUKDONG",
                "LX-203=JY-203",
                "SD-689A",
                "KD-BCM4C8B",
                "KD-BCM4H4C",
                "SD-689E",
                "HJ-AD1",
                "LB-727",
                "EF-526MAS",
                "CF-739MA",
                "HJ-DHC",
                "SD-939",
                "KD-87A",
                "SD-938B",
                "KD-C450RA",
                "KD-C450RA-R",
                "KD-SS1/T",
                "KD-HL3",
                "KD-HS1",
                "KD-DP9/A-N/T",
                "KD-TSB4",
                "KS-40M",
                "KD-AP5",
                "SH-501A",
                "SD-939-S",
                "KD-DP9/A-BN",
                "KD-S9",
                "C500DA-S",
                "KD-DP9/F-BN",
                "JT-8003A",
                "ZS-380C/B",
                "ZS-380K",
                "HD-5016T",
                "KD-AL1",
                "KD-H9-J-N",
                "SD-938B2",
                "ZS-630C/B",
                "KD-TJ2D",
                "KD-MDL1",
                "SH-136B",
                "TY-206",
                "D622/30-LDI(NO",
                "D622/30-LDI(SER",
                "CMA-1810FVT-B(8",
                "CMA-1610FET-D-8",
                "CMA-1610FET-C-8",
                "OSP-10D",
                "OSP-10F",
                "RS005L",
                "JS-801NIR",
                "KD-BCM5D",
                "HJ-103",
                "OFA-210",
                "OFA-220",
                "JY-501",
                "SD-688E",
                "TJ-2",
                "TJ-2E",
                "CZ/L",
                "CZ/L (CZL075U04",
                "CZ/L (CZL075U05",
                "CZ/L (CZL02V002",
                "CZ/L (CZL02V003",
                "CZ/L (CZL02V004",
                "CZ/L (CZL02V005",
                "CZ/L (CZL02V006",
                "CZ/L (CZL200V01",
                "CZ/L (CZL200V03",
                "CZ/L (CZL200V04",
                "CZ/L-CZL240Z016",
                "CZ/L-CZL240Z017",
                "CZ/XL",
                "RAZOR 25",
                "KD-P3",
                "KD-P2",
                "HM-1610-100W",
                "CMA-1610FET-D10",
                "CMA-1610FET-D-1",
                "CMA-1810FVT-C(8",
                "CMA-1610FET-C-1",
                "CMA-1610TEF-80W",
                "SP588/3-EX - 25",
                "SP588/3-EX-25TO",
                "TW-588/3-25TON",
                "120C-EX-20TON",
                "HSD/Q250A",
                "SH-135H",
                "AGP-600S",
                "HEAM-2HC",
                "KD-G4N",
                "HEAM-UV",
                "HS-7002A-A114",
                "HS-7002A-A103",
                "DBA-4072-6A-SE",
                "HL-1200TCH",
                "JS-836T",
                "CZ/L-CZL240Z015",
                "SY-525-25TON",
                "KD-P3-C",
                "VS-922",
                "CMA-1610TEF-130",
                "CMA-1610TF",
                "CMA-1610TF-80W",
                "HJG-LTK-1G",
                "KD-LP1",
                "STITCHING",
                "6300X800X1200",
                "ZS-430C/B",
                "VS-918-T20",
                "SD-957(F)",
                "KD-BCM2H2C17",
                "CZ/L(CZL200V122",
                "CZ/L(CZL200V169",
                "KD-TS4",
                "SD-2020-01/A",
                "MS-168",
                "CT/M-VR (CTM070",
                "CZ/M-CZM040Z007",
                "CZ/P",
                "KD-M3",
                "KD-AL1A",
                "KD-G4",
                "KD-G5",
                "HJ-BF50",
                "JMT2-12KWHO",
                "KD-105B-5T",
                "CY-AFPX1A",
                "HJB-R131",
                "KD-20TNH-D",
                "KD-PP1",
                "CY-LAS755A2ZAFE",
                "HL-1500FHA",
                "HL-FH",
                "AN-102SP",
                "JMT2-N500",
                "SJ-102SP",
                "HM-450",
                "FL-450",
                "ICN-B100",
                "UVC-1014+1023W",
                "UVC-655+204W",
                "HJ-OSW1",
                "F1UV",
                "C1200DU",
                "UVC-1014WAD",
                "SD-688NIR",
                "HJ-VGD1",
                "CSK-13-01/MA",
                "SH-530",
                "TBC-50LH",
                "SH-50SH",
                "CS-7-03",
                "CS-7-03A",
                "SWF/C-WB(X)620-",
                "SWF/C-WD906-55",
                "LATEX+STEAMER",
                "WP-6",
                "NT/XXL",
                "DR-CNC (SERIAL",
                "C1200DS-S",
                "VERSION 1.2",
                "HJ-OSW2",
                "ZS-620C/B",
                "ZS-620C/BII",
                "YM-7060-3PC-CK",
                "XD-3D-SM-02",
                "KD-BCM2H2C",
                "HJ-101",
                "CF-640ES",
                "KD-AP7",
                "PR-20000HKAE",
                "JY-890",
                "KD-G2",
                "M800",
                "KD-CYC74",
                "GS-518",
                "SH-530L",
                "HXST-12000",
                "KD-10TNB-L",
                "JM-120",
                "HXST-10000",
                "SH-137",
                "AN-15HFW",
                "KD-20TNH-L",
                "TLC-731",
                "CZ/L (CZL200V05",
                "CZ/L(CZL200V082",
                "CZ/L(CZL200V083",
                "JCV21-1707JSMC",
                "KD-HB6",
                "KD-BCM4C",
                "HL-FH2",
                "SD-957 (8.3M C/",
                "KD-S6",
                "CY-LAS755A2-E",
                "CY-LAS755A2-AFE",
                "NSV-C90X-2COLOR",
                "C500DS-S",
                "SD-911D",
                "HYEKWANG",
                "SD-957ZH",
                "LINX-5900",
                "TR-3N",
                "KD-EH2",
                "ZS-630E",
                "JY-8615",
                "JY-201",
                "KS-WR100(D TYPE",
                "DBA-6080-6A-SE",
                "XLBD 500*500*2",
                "KD-TDL-150-4",
                "ATDL-M(2)",
                "CT-2002",
                "TZLHD-6S",
                "TK-R300F",
                "SHT-101",
                "CF-928",
                "LX-515-2A",
                "SD-828",
                "KD-IPD2",
                "PH-866CL",
                "6100*1500",
                "KSC-908LE2",
                "BCO-15-5S",
                "TS-DB2",
                "KSC-910GP2A",
                "KSC-904GPS2",
                "KSC-908GP2",
                "KSC-908ULC2",
                "SH-ECH400-4",
                "KD-AM1/1F",
                "KSC-216FN4",
                "KSC-216FL3",
                "STCS-3",
                "YS-2050-5TON",
                "6100X1500",
                "KSC-906LE2",
                "TY-204T-4S-A",
                "KSC-9906E2",
                "5500L*800W",
                "5500L 800W",
                "DS-1000",
                "TY-204T-8S-A",
                "BCO-15-5S/1F",
                "1170X1170X1605",
                "KD-IPC",
                "SHM-209",
                "JMF2-12KWHO",
                "JM500-1",
                "HW-20C",
                "SHB-206",
                "TC-BM01",
                "CZ/L-CZL240Z018",
                "HCM-F6026",
                "JV300-160 (S962",
                "JV300-160 (S963",
                "JV300-160 (S273",
                "C500DA-F",
                "MOD 200",
                "KD-AP",
                "LATEX",
                "SD-1M",
                "CZ/L(CZL200V170",
                "CZ/L-CZL240Z006",
                "CZ/L-CZL240Z007",
                " ",
                "WS3712AC(SERI:3",
                "TBC-50H",
                "SD-L19HH",
                "D622/08-LDI (SE",
                "CT-4200XL-110/2",
                "AWS168-RUBBER",
                "AWS168-EVA",
                "LBC-100RT",
                "80KG",
                "SJF-D65X90X65X1",
                "JKM-165KE",
                "XY-350X2/500X2",
                "OHI-60 (SR17090",
                "XY-C120 2400MMM",
                "DONGHWA",
                "HD-2005B",
                "SJS-1500L",
                "VMP-201",
                "2M",
                "SHXJ-B800",
                "QS-MN45",
                "RQL-800",
                "HX-831203+81051",
                "BS-M08S",
                "BS-K10",
                "KD-C1",
                "XK-560",
                "JY-986",
                "ASY-B800",
                "JY-5000TAH 5-KW",
                "CZ/L-CZL240Z042",
                "CZ/L-CZL240Z043",
                "CZ/L-CZL240Z044",
                "KS-WR200",
                "JY-580A",
                "EL-181LS-3",
                "WR-128-01",
                "AP-1212Y",
                "ZS-650C/B",
                "SPS/A-1507HS-10",
                "8700X1000",
                "MAV-10",
                "TS-701AU",
                "KD-RCI600",
                "KD-AM1/2F",
                "JG-901",
                "KD-P150",
                "ZZ-A01",
                "ZZ-CH-01",
                "PL-8006A-B",
                "JG-801",
                "ZZ-O-02",
                "JG-903",
                "PL-5006(=5003*2",
                "PL-2002",
                "ZZ-CO-01",
                "TURBO-FROST4",
                "TF-5",
                "HEAM-5D",
                "KD-QC2",
                "USM TPS-2",
                "LJ-826",
                "TYL-570A",
                "WJ20S",
                " ",
                "C300DA-S",
                "HEAM-5K",
                "HJ-102",
                "DALIAN",
                "KD-S4",
                "SHL-100",
                "HJ - CLM300",
                "OPTIM",
                "HJ-WBS3",
                "HJ - WBL1",
                "JYF-02G",
                "GYMSD-600.450",
                "HJP-CR2",
                "HJP-CR3",
                "HJI-OB180",
                "HI-ETH100",
                "XN-75L",
                "DTJ-75",
                "BS-M18S",
                "XK-450(18INCH)",
                "5HP",
                "HJ-1300TON",
                "RB-720ALE-13L",
                "HEAM-SF",
                "ZHM-450A",
                "ARN-W420",
                "YB-110L",
                "YB-22",
                "RSS-01-O",
                "KD-AP13",
                "XC-8HP",
                "XC-10HP",
                "GFQ1800",
                "QS-2G60",
                "QS-ABC800",
                "KD-OP2",
                "TURBO BELT600",
                "SD-938L",
                "TURBO FPOST2",
                "KD-GM75",
                "SH-129",
                "KD-AP9",
                " ",
                "HJ-VGD2",
                " ",
                "LBC-50RT",
                "SH-7035",
                "XT-S-1200",
                "ST-8500M-4",
                "ST-757-7",
                "ST-967BN",
                "ST-957-7LS",
                "TS-205",
                "TS-204",
                "FA-1000N",
                "SH-137B",
                "SHL-500",
                "DS-CG-2013",
                "HDX-400",
                "JY-339",
                "KM-1967-7",
                "KD-HB4-N",
                "HEAM-1B",
                "USS4",
                "ZD-1000",
                "SHB-205",
                "SHB-204",
                "ST-3020HS-5P",
                "ST-3020HS-C2",
                "1M",
                "AGP–N700A",
                " ",
                " ",
                "CZ/L-CZL240Z008",
                "CZ/L-CZL240Z009",
                "A-8",
                "KD-OP3",
                "JW-100",
                "TS-110L",
                "1660 BP (SERIAL",
                "HXS-8000WA",
                "JWZ-BM30",
                "JWZ-BM05D",
                "C2000DS",
                "FA-450",
                "PREMOULDER N-23",
                "ND-80",
                "HD-100",
                "JV300-160 (S996",
                "JKM-DK5,9MR,65K",
                "K-22",
                "GY-LWE1636",
                "GY-SBB1921",
                "GY-HXA1520",
                "CZ/M-CZM040Z006",
                "JY-10000TCH",
                " ",
                "HSYT-350F",
                "USY-525",
                "JWELL",
                "SHL-300",
                "EMBO150",
                "NE-250D",
                "BTTYW085-B",
                "KD-DB2",
                "NED-280",
                "1100490",
                "600X3000",
                "6015",
                "DMC-U1300D",
                "NSM-T",
                "DJB-75",
                "BY-SZ6010-SF",
                "BY-ZT6010",
                "BY-IR6010",
                "DAILAN HUAHAN",
                "K-CV",
                "YL-8815D",
                "CZ/L-CZL240Z041",
                "LEP-15",
                "MGA-QDD20 (2.0T",
                "MGA-QDD30 (3.0T",
                "MGA-TC10-50 (1.",
                "2FLOOR X 2M",
                "JY-15000HSCK",
                "YJ-8503-1",
                "KD-220915-HSV",
                "FB15-8",
                "K-110",
                "6300X700X1200",
                "KMS030D3-01(DHM",
                "W1100*L5500",
                "W1500*L7100",
                "JHM-DK35",
                "MN-75",
                "EXT-C180JA",
                "K-18",
                "K22",
                "JY-8832D",
                "TK-278-8H10C",
                "ZHM210",
                "2800X3300X3000",
                "XY-75-800MM",
                "ML85/33",
                "500KG",
                "ZY-329T",
                "ZY-339T",
                "NP-200SJ",
                "TK-361-6SL-E",
                "TURBO-125HVA",
                "JS-230-BZ",
                "STCS-4",
                "KN-10WC",
                "HBP-H-100",
                "PM-35T",
                "JS-230-BZ(217A)",
                "JY-5182CQ2HQ",
                "KD-HG1-N",
                "JY-QD2",
                "KD-QC1.6M",
                "KD-QC2.4M",
                "KD-HSC1.5M",
                "KD-UVC3.2M",
                "GRH3GS-50A",
                "TURBO JET2",
                "AGP-N600S",
                "FA-1600N",
                "CL-8698-XT",
                "BNS-320",
                "LBC-200RT",
                "TMQ-SF2000",
                "CZ/L(CZL070R005",
                "CZ/L(CZL035P020",
                "CZ/L(CZL035P021",
                "CZ/L(CZL035P019",
                "CZ/L(CZL075U045",
                "CZ/L(CZL075U046",
                "CZ/L(CZL200V015",
                "CZ/L(CZL200V036",
                "CZ/L(CZL200V040",
                "CZ/L(CZL200V038",
                "CZ/L(CZL200V041",
                "CZ/L(CZL240Z006",
                "CZ/L(CZL240Z008",
                "CZ/L(CZL240Z016",
                "CZ/L(CZL240Z017",
                "CZ/L(CZL070R004",
                "CZ/L(CZL070R006",
                "CZ/L(CZL070R007",
                "CZ/L(CZL035P022",
                "CZ/L(CZL075U044",
                "CZ/L(CZL075U057",
                "CZ/L(CZL075U058",
                "CZ/L(CZL075U059",
                "CZ/L(CZL200V002",
                "CZ/L(CZL200V003",
                "CZ/L(CZL200V004",
                "CZ/L(CZL200V005",
                "CZ/L(CZL200V006",
                "CZ/L(CZL200V013",
                "CZ/L(CZL200V014",
                "CZ/L(CZL200V016",
                "CZ/L(CZL200V017",
                "CZ/L(CZL200V037",
                "CZ/L(CZL200V039",
                "CZ/L(CZL200V059",
                "CZ/L(CZL200V184",
                "CZ/L(CZL200V185",
                "CZ/L(ZL240Z007",
                "CZ/L(CZL240Z009",
                "CZ/L(CZL240Z015",
                "CZ/L(CZL240Z018",
                "CZ/L(CZL240Z041",
                "CZ/L(CZL240Z042",
                "CZ/L(CZL240Z043",
                "CZ/L(CZL240Z044",
                "856 (SERIAL 201",
                "RHD8-TR",
                "KM-957-7S",
                "TAIWAN",
                "JY-203",
                "W2000X1500XH210",
                "1900LX1200WX195",
                "2510X1670X2900",
                "TAM-HG20",
                "KD-DP9/F-N",
                "ST-2002HT",
                "DS-10C",
                "GRH3GS-100A",
                "HJ-D21",
                "TMQ-SF22M",
                "KD-H9C-F",
                "KD-DP9/A-N",
                "KMS020D3-01",
                "TMQ-QC3.5M",
                "20HP",
                "KD-TSB2",
                "CBD15(080157M01",
                "TG20(2000KG)",
                "CBD15(080157M17",
                "GT-7190",
                "FOR D622/08-LDI",
                "FOR D622/30-LDI",
                "W1320*L11000*H1",
                "KD-QC3.0M",
                "KD-S6-N",
                "CBD15(080157N07",
                "HD-192B",
                "TY-204T-8S-A-2J",
                "JY-187A",
                "GT-7017-EL1",
                "GRH3-50A",
                "GRH3-100A",
                "GRH-100A",
                "GRH2-100A",
                "AS-200HA",
                "XS-125A(SERIAL:",
                "CT/M-VR > CZ+L0",
                "S2-5616-P(X1-16",
                "G2-1605 (G2-431",
                " G2-1605 (G2-4316)",
                "S2-5616-P(X1-1616)",
                "G2-1605",
                "H2800*W1150*",
                "H2800 X W1150 X",
                "LC-PM1-100",
                "HJ-EL2",
                "JY-525-25TON",
                "SFT-10606",
                "AI-3000-U",
                "GT-7012-D",
                "KD-QC3.5M",
                "TMQ-QC3.8M",
                "20MX3CHAMBER",
                "26MX4CHAMBER",
                "TMQ-UVC-15MX2CH",
                "50R/T-SWRS050E",
                "HJ-OB180",
                "HS-VINA",
                "HSYT-250FT",
                "ZUND S3 M800TZP",
                "HJ-109",
                "ONESTAR M",
                "MD-3000FA",
                "HDMBST1705001/C",
                "HDMBST1707001/C",
                "HDMBST1710001/C",
                "3800X6260X3800",
                "JIAN KWANG",
                "GYDBK-1800",
                "SWP360E",
                "XMF-300",
                "K110",
                "DSP-1100S",
                "H-600D",
                "OSS-22",
                "HEAM-7N",
                "S2-5616-P",
                "HJ-EX6",
                "CF-639MA",
                "JY-209",
                "KD-HB8",
                "KD-OP4",
                "LC-30A",
                "HN-IW1",
                "W2000XL1100XH16",
                "VSM-420 1/2 HP",
                "HRM-48",
                "HOA DON 459/171",
                "HEAM-SM",
                "KEBF 250",
                "YM-7006-5IC",
                "015/2021/HDMB T",
                "CBD15(080157T90",
                "UT-52",
                "HJ-TB5",
                "BS-K/D-75-S",
                "BS- M16S",
                "BS- M22S",
                "BS-M22S",
                "10HP",
                "7.5R/T",
                "JKM-180KE",
                "3STEPX8STATION",
                "SH-B1",
                "TYL-966A",
                "LV11,LV21,LV31",
                "LV41 42 43 TB",
                "LV41,51 61 TB",
                "LV11 21 31 TB",
                "LV11 21 TB",
                "LV31 41 TB",
                "EL-181A",
                "TSC-HS028",
                "SAY CHONG NHAN",
                "C2000DU",
                "JHM-CDK10 +C75K",
                "INFINITI AGV-CC",
                "ST-6003",
                "ST-957BN",
                "D-35C-5",
                "HG-858",
                "FOM71CLS",
                "CI60-MEDIUM APE",
                "XLS + (II) WB30",
                "RHD8",
                "TLP-1160*500*30",
                "TA120",
                "CF-625T",
                "SJ-10HFW",
                "SC-50",
                "CBL-335",
                "OSP-02D",
                "TH300PU-ST-2M",
                "OPS-410",
                "NH-10",
                "P-1000",
                "CPD15J(1.5TON)",
                "35DF-7",
                "FD35T3S",
                "TCM-RT12-8",
                "EX324",
                "MGA-EW-10",
                "NEC-3015D",
                "ELEP-15",
                "HD1707010/KMS02",
                "HD1707010/KMS02",
                "AI-7000-SU1",
                "SUNSTAR",
                "DEASUNG",
                "SUN TECH",
                "SUN TECH",
                "JP6040T10B",
                "RSS-03-P-2C",
                "JY-8848C",
                "ZUND S3 M800",
                "HJ-TBAB75",
                "KD-BW2",
                "KD-BW1",
                "SHM-701",
                "35/2015/HKT",
                "SH-7",
                "KD-P1500",
                "HJ-TBA50",
                "HJ-C12",
                "SY-AF55",
                "HJ-SS45",
                "BS-C12",
                "NH-20",
                "GS-250SL RT 5X5",
                "HJ-P04",
                "ATDL-M(4)",
                "SCANER-7",
                "TS-9136B",
                "GDV-50HA",
                "ZUND-S3 M800",
                "ZUND",
                "UM-2050",
                "MDR-U6",
                "HC-335",
                "6300FGD",
                "WEINMANN",
                "KD-APS",
                "HSD PUR ACTIVAT",
                "800XH1800XL1800",
                "A9 PRO",
                "ST-FR5",
                "AUBO I5",
                "HS PUR ACTIVATO",
                "CH-10 & CH-12",
                "HD-504B",
                "CPD10-1.5",
                "FRSB16-8",
                "FB20-8",
                "MGA-3.0T (SERI",
                "LD30TC (SERI 15",
                "FB15-8 (7P13488",
                "FB15-8 (7P13490",
                "INFINITI AGV-11",
                "FB20-8 (7P34022",
                "ES-100/45",
                "SO -29F18HSV",
                "MGA-ES-20M",
                "HD98/161024",
                "J60EX",
                "MF20-E-A",
                "TTH",
                "HD147/170425",
                "14.HDMB.DMT.HW",
                "15.HDMB.DMT.HW",
                "16.HDMB.DMT.HW",
                "17.HDMB.DMT.HW",
                "18.HDMB.DMT.HW",
                "CONTRACT 04.HDM",
                "05.HDMB.DMT.HW",
                "TA-80",
                "ZZ-SP",
                "JY-8815D",
                "JY-1800",
                "SJ-HFDR-D6",
                "SJ-COOL-3P",
                "SJ-COOL-3P-30T",
                "HD30/CT-HDKT",
                "FR030AP",
                "EF-526MAX",
                "EF-889MAX"
            ]),
            mt_cd: faker.string.nanoid(10),
            mt_nm: faker.helpers.arrayElement([
                "1 side Folding MC",
                "1.5TON AC ELECTRIC FORKLIFT",
                "1.5TON ELECTRIC PALLET TRUCK",
                "1.5TON FULL AC ELECTRIC FORKLIFT",
                "1.5TON FULL AC ELECTRIC FORKLIFT",
                "10 STATION SOLE PRESS M/C",
                "10L Kneader",
                "10M Dry Conveyor With 2M Heating Chamber",
                "120 Station Conveyor",
                "12Inch Three Roll Calender M/C",
                "1300TON SPONGE PRESS",
                "150TON Hot Press M/C",
                "18 Inch Mixing Roll",
                "2 HEAD 3D PNEUMATIC HEEL NO SEW PRESS MC",
                "2 HEAD 3D PNEUMATIC HEEL NO SEW PRESS MC",
                "2 needles Flat Stitching MC",
                "2 STEPS  ROLLER PRESS M/C",
                "2.0TON AC ELECTRIC FORKLIFT",
                "22\" Mixing Roll M/C\"",
                "3 Needles Flat Machine",
                "3 Needles Post Machine",
                "3-LAYER LLDPE  FILM EXTRUSION  REWINDER",
                "3.5 TON DIESEL FORKLIFT ",
                "30 Station",
                "3D HEEL FORMING M/C",
                "3D PRINTER M/C",
                "3D Steaming M/C (4 Station)",
                "3WAY ELECTRIC FORKLIFT",
                "3WAY ELECTRIC FORKLIFT 1.2 TON",
                "4 Needles Flat Machine",
                "5TON THOMPSON CUTTING M/C",
                "8 Station",
                "8\"Mill Test\"",
                "90mm One Color Pad Printer",
                "Activator M/C",
                "ADHESION TAPPING M/C",
                "AGING OVEN",
                "AIR BAG TUBLING M/C",
                "Air Cooled Chiller M/C 30RT",
                "Air Press Machine",
                "Air Tank 1L",
                "Arian",
                "Assembly Conveyor",
                "ASSEMBLY LINE",
                "ATOM FLASHCUT 2H 1660 BP UP M/C/",
                "Auto Eva Moulding Press",
                "Auto Heel Seat & Side Lasting ",
                "AUTO HEEL SEAT AND SIDE LASTING WITH HOT",
                "Auto Last Puller",
                "Auto Measuring & Drying Oven",
                "AUTO MIXER M/C / MAY TRON TU DONG",
                "AUTO MOLD WASHING M/C/MAY RUA KHUON",
                "Auto Outsole Press ",
                "AUTO SIZE LABEL PRESSING M/C",
                "Auto Sliding Table High Frequency Welder",
                "AUTO SLIDING TABLE HIGH FREQUENCY WELDER",
                "Auto Sliding Table High Frequency Welder M/c",
                "AUTO SPRAY MACHINE/MAY SON TU DONG",
                "AUTO TABLE PRINTING M/C",
                "AUTO TRANSFER & LABEL PRESSING MACHINE",
                "Auto Tridimensional Cycle Priting",
                "Auto UV Sray Machine",
                "Auto Weighing",
                "AUTO-SHOE PADS TRANSFER PRINTING",
                "Automatic Counyer Shaping M/C",
                "Automatic Embroidery",
                "Automatic Eyeleting",
                "AUTOMATIC GUIDED VERHICLE (AGV)",
                "Automatic Outsole TDL Press",
                "Automatic Thread Winder",
                "Automatic Ultrasonic Tape Cutting Machine",
                "BACK COUNTER HEATING BLOWER",
                "Back Counter Heating Blower",
                "BACK COUNTER MOULDINGM/C",
                "Backpart Molding Machine",
                "Ball melt",
                "Beating M/C",
                "BENDING M/C / MAY UON DAO",
                "BIAS TAPE CUTTING M/C",
                "Bias Tape Rolle Machine",
                "BLOW MOLDING M/C",
                "BON TRON VAT LIEU IMEVA-MIXER TANK",
                "Bottom Groughing and Dust Collector ",
                "BRONZING M/C",
                "Buffing Grinder",
                "Buffing Grinder and  Dust Collector",
                "Buffing Grinder With Dust Collector",
                "BUFFING GRINDER WITH DUST COLLECTOR",
                "CARTON BOX AUTO TAPING MACHINE",
                "CELLFLEXER STATION(STOCKFIT LINE)",
                "CHAMBER",
                "CHILLER",
                "CHILLER 10HP",
                "CHILLER 8HP",
                "Chilling M/C",
                "CNC MACHINE",
                "COLD PRESS SETTING MACHINE",
                "Colling Tower ",
                "Com 1010",
                "Com 1306",
                "Com 1310-Sunstar",
                "Com 1310-Suntech",
                "Com 1507",
                "Com 1510",
                "Com 2010 SewQ",
                "Com 2020 supreme",
                "Com 2210",
                "Com 2516",
                "Com 3020 SewQ",
                "Com 3020 Sunstar",
                "Com 3020 Suntech",
                "Com 3020 Supreme",
                "Com 3020-2 Color",
                "Com 3020-5 Pallet Slide",
                "Com 5030",
                "Com 5050",
                "Com 6040",
                "Comelz Cutting Machine",
                "Compound Blender",
                "COMPRESSOR AIR DRYER",
                "Computer embroidery",
                "COMPUTER EMBROIDERY M/C 6-HEAD",
                "Computer Head Seating & Cold Cutting Bag",
                "Computer punching - Suntech",
                "Computer punching - Supreme",
                "Computer stitching & Punching",
                "Computer Webing Folding - eyestay",
                "Computer Webing Folding - tongue",
                "COMPUTERIZED LEATHER MEAURING MACHINE",
                "Computrac Vacpor Pro XL",
                "Continuous Straight Fusing",
                "Cooling HD Molding Press M/C",
                "COOLING TOWER 50RT",
                "CRUSHING MACHINE",
                "Cutting 62\" Machine\"",
                "CUTTING MODULE M/C",
                "Cyclone (74 STATION)",
                "DEHUMIDIFIER M/C",
                "DEHUMIDIFYING DRYER M/C",
                "Delasting",
                "DENSICOM TESTER M/C",
                "DENSICOM TESTER M/C",
                "DESICCANT AIR DRYER ",
                "Dewaterer",
                "DISPERSION KNEADER 75L",
                "Dispersion Kneader M/C 35L",
                "Dosing Unit",
                "Dosing Unit",
                "DOUBLE  HEAD SIDE ROUGHING M/C",
                "Double Color Three Tank M/C",
                "Double Folding",
                "Double Side 3D UV Curing Machine",
                "DOUBLE STATION BLOW MOLDING M/C",
                "Drum Heater Oven",
                "DUAL-AIXIS FREQUENCY CONVERSION AUTOMATI",
                "Dust Collector ",
                "E.V.A  WEDGE SKIVING DOUBLE M/C",
                "E.V.A Band Knife Splitting M/C",
                "E.V.A DIGITAL BAND KNIFE SPLITTI",
                "E.V.A RECYCLING MACHINE",
                "E.V.A. Pelletizing Whole Plant Equipmen",
                "ELECTRIC FORKLIFT (STAND DRIVING TYPE)",
                "ELECTRIC HEATING BOILER(NOI HOI DIEN)",
                "ELECTRIC HEATING BOILER(NOI HOI DIEN)",
                "Electric Heating Oven",
                "ELECTRIC TOW TRUCK",
                "ELEVATOR FOR MIXING ROLL",
                "ELEVATOR FOR MIXING ROLL",
                "EMBOSING PRESS M/C",
                "EMMA ",
                "etc Flat zigzac MC",
                "etc Post zigzac MC",
                "EVA COLOR PAD PRINTER M/C",
                "Eva Injection Molding M/C",
                "EXTRUDER M/C ",
                "Eyelet MC",
                "FDM INDUSTRIAL GRADE 3D PRINTER",
                "Finishing Grinder",
                "FLASH ACTIVATOR MACHINE",
                "Flash Activator Machine",
                "FOAM SKIVING MACHINE ",
                "FORM PRESSURE RHEOMETER",
                "FOXING TAPE BUFFING M/C",
                "Full Auto High Speed Y-Shirt Bag Making ",
                "FULLY AUTO TUMBLALE",
                "Gathering",
                "Gauage Marking",
                "GENERATER",
                "GLUE MIXER M/C",
                "Hammering",
                "Hand Grinder Hood and Dust",
                "Hardo Thermo 150 Pu Roller Coating ",
                "HDPE Film Extruder Unit",
                "Heat Transfer M/C (VSP)",
                "Heating Flat Board Press",
                "HEEL 3D NO-SEW ",
                "HEEL 3D NO-SEW M.C",
                "HEEL 3D NO-SEW M.C",
                "HEEL 3D NO-SEW M.C",
                "HEEL 3D NO-SEW M.C",
                "Heel Heating Press M/C",
                "Heel Laster",
                "HELL HEATING PRESS M/C",
                "HIGH FREQUENCY DUAL RESONANCE HEAT PRESSING MACHIN",
                "High Frequency M/C",
                "High Frequency M/C",
                "High Frequency Welder M/C",
                "High Frequency Welder M/C",
                "High Frequency Welder M/C 5-KW",
                "HIGH SPEED BAND-KNIFE SPLITTING(MÁY LẠNG)",
                "High Speed Hole Drilling M/C",
                "HOPPER DRYER",
                "Hot Melt KS-WR200",
                "Hotmelt",
                "Hotmelt Roll Coater For Insole",
                "Hotmelt Roller Coating ",
                "HY'D STEEL HOLE PUNCHING M/C",
                "Hyd Hot Press",
                "Hyd Movable Cutting M/C ",
                "HYD OUT SOLE PRESS",
                "HYD PLANE CUTTING 63\"(25TON)\"",
                "HYDAULIC OIL FILTER MC",
                "Hydraulic Hot Press M/C",
                "HYDRAULIC PLANE CUTTING (25TON)",
                "HYDRAULIC PLANE CUTTING/MAY CAT DAP",
                "HYDRAULIC SIDE PRESS",
                "HYDRAULIC TOE & HEEL PRESS",
                "HYDRAULIC WALED SOLE ATTACHING",
                "Ice Machine 5HP",
                "Im Eva Extruder M/C",
                "Imeva Sole Cutting M/C",
                "IMEVA SOLE CUTTING M/C/MAY HUY DE GIAY",
                "INDEPENDENT WALKING DRYER",
                "INDUSTRIAL DEHUMIDIFIER/HUT AM CONG NGHI",
                "Insole Hotmelt",
                "INTENSIVE MIXER 75 ( BAMBUMRY)",
                "IP Rotary Machine (Tumbling)",
                "IP Sole Inspection M/C",
                "IP WASHING MACHINE",
                "IP Washing Machine",
                "KNEADER ",
                "Kneader 75L M/C",
                "Kneader Extruder + Underwater Cutting SYS",
                "Label Cutter",
                "Label Cutting Machine",
                "Label Stamping  Machine 2 Head ",
                "LAGANG M/C",
                "LAMINATING M/C",
                "Laser Cutting Machine",
                "Latex Conveyor",
                "LATEX DRY CHECK CHAMBER",
                "Latex Dry Check Chamber",
                "LATEX DRY LIFT TOWER",
                "LATHE M/C",
                "Leather Buffing and Dust Collector ",
                "LEATHER MEASURING WITH METAL DETECTOR",
                "LECAF M/C (INVOICE KD-220915-HSV)",
                "LINX INK JET PRINTER M/C (UV STAMPING)",
                "MAL SHOE CRUSHING M/C",
                "MAY MAY BAO",
                "MILL M/C",
                "Mimaki Double Print Head Inkjet Printer",
                "Mixer Tank",
                "MIXING ROLL M/C\"",
                "Mold Cleaning M/C",
                "MORGAN",
                "Multi Press 600",
                "NEEDLE DETECTOR M/C",
                "NEXT GENERATION SERVO-CONTROLLED CEMENT",
                "No Sew Press",
                "Non Pad Gel Press Machine",
                "OFF-LINE NESTING TABLE",
                "One Color Eva Injection Moulding ",
                "Out Sole Grinder",
                "OUT SOLE WASHING & DRY M/C",
                "Outsole Buffing",
                "OUTSOLE BUFFING (MÁY MÀI ĐẾ)",
                "OVEN(HALOGEN CHAMBER)",
                "Overlock",
                "PE Double Head Film Blowing M/C",
                "Pioneer of Shoe Making M/C",
                "PISTON AIR COMPRESSOR 5HP",
                "Piston Air Compressor 7.5KW",
                "PLASMA SHOE PRE-TREAMENT MACHINE",
                "PLASTIC LAST HOLDING DEVICE",
                "PNEUMATIC HEAT PRESS M/C",
                "PNEUMATIC HEEL PRESSING  M/C",
                "Pneumatic Hot Press M/C",
                "PNEUMATIC SOLE  PRESSING  M/C",
                "Poly Bag Film Making M/C",
                "POLY BAG FILM MAKING MC",
                "POLY BAG FILM MAKING MC",
                "POLY BAG FILM MAKING MC",
                "Poly Bag Making M/C (Bottom Sealing)",
                "Poly Bag Making M/C (Side Sealing)",
                "Poly Bag Making M/C (Single line)",
                "Poly Bag Making Machine",
                "POLY BAG PRINTING M/C",
                "Poly Bag Recycle M/C",
                "Pong Pong Machine",
                "POST Q LIFT CONVEYOR",
                "Post Stitching MC",
                "Power Punching",
                "Pre Press M/C",
                "pro-test",
                "Punching MC",
                "Questa Machine Deve Essere Messa A Terra",
                "Quick Chilling",
                "QUICK CHILLING M/C-3.5M",
                "QUICK CHILLING M/C-3.8M",
                "RAPID OSA SYSTEM(PUR ROBOT SYSTEM)",
                "RAPID PUR SYSTEM (PUR ROBOT SYSTEM)",
                "RAPID PUR SYSTEM (PUR ROBOT SYSTEM)",
                "Raw Rubber Cutting M/C",
                "ROBOT OUTSOLE SPRAY SYSTEM",
                "Robot System Automation",
                "ROLLER MIXING 18\" X 48\"\"\"",
                "ROLLER MIXING 18INCH X48L",
                "ROOLS HODER DIVICE(THANH CUON LIEU MAY C",
                "ROTARY AUTO SIZE LABEL PRESSING M/C",
                "Rotary Dual Color Eva Injection M/C",
                "Rotary Eva Hot & Cold Molding M/C",
                "Rubber Compression Molding M/C",
                "Rubber Deflashing M/C",
                "Rubber Injection Molding M/C",
                "RUBBER MILL UNIT",
                "Scewr Air Compressor ",
                "SCREEN DRY OVEN M/C",
                "SCREEN DRYER",
                "SCREEN PLATE MARKING M/C",
                "Screw Air Compressor ",
                "SEMI ELECTRIC STACKER (Xe nâng tay điện - có càng ",
                "SEMIAUTOMATIC WRAP MACHINE ",
                "Skiving",
                "SMART CUTTING M.C",
                "SMART CUTTING M.C",
                "SMART CUTTING M.C",
                "SMART CUTTING M.C",
                "SOCK LINEAR PRESS",
                "SOCK LINEAR PRESS (AIR INSLOE PRESS) M/C",
                "SOLVENT RECYCLER M/C",
                "Spary Booth",
                "Spray",
                "Stamping Machine",
                "STICKER LABEL MAKING M/C-MAY LAM TEM NHA",
                "STOCKFIT DRY C/V (22M X 8 CHAMBER 2M)",
                "STOCKFIT LINE",
                "Stockfit Line (3 Chamber)",
                "STOCKFIT LINE (ADIDAS)",
                "STOCKFIT LINE-DOUBLE(24.3M X 4CHAMBER)",
                "STRAIGHT WINDING M/C",
                "Strobell",
                "Sunstar 2 Needles Post Stitching MC",
                "Sunstar Flat Stitching MC",
                "Sunstar Flat zigzac MC",
                "Sunstar Post Stitching MC",
                "Suntech 2 Needles Post Stitching MC",
                "Suntech Flat Stitching MC",
                "Suntech Flat zigzac MC",
                "Suntech Post Stitching MC",
                "Suntech Post zigzac MC",
                "Swing Arm Cutting",
                "Tape Machine",
                "Textile Measuring M/C",
                "Textion Movable Heat Type Cutting ",
                "TEXTION MOVABLE HEAT TYPE CUTTING M/C",
                "Thermo Printing With Vacuum Function",
                "THERMOPLASTIC COUNTER PREMOULDING M/C",
                "THERMOPRINTING MONTI ANTONIO 856",
                "Thermostatic Oven Dryer",
                "Thermostatic Oven Dryer (1FLOOR)",
                "Thermostatic Oven Dryer (2 FLOOR)",
                "Thermostatic Oven Dryer (2 Floor)",
                "TOE HUMIDIFYING PRESS",
                "Toe Laster Machine",
                "TOE LASTING MC FOR US SPORTS",
                "Toe Molding Machine",
                "Toe Steam Conditioner ",
                "TPU CRUSHER M/C",
                "TPU FILM COATING COMPOUND LINE",
                "TPU WASHING M/C/MAY NHUNG TPU",
                "Trimming",
                "TRIMMING M/C",
                "TU DIEN ACB,MCCB, TU BU",
                "TWO COLD AND TWO HOT COUNTER MOULDING M/",
                "Two Color Eva Injection Molding M/C",
                "Two Color Pad Printer",
                "Two Roll Mixing Mill 22\"\"",
                "Ultrasonic Pressing Circle Machine",
                "Unicon 2 Needles Post Stitching MC",
                "Unicon Flat Stitching MC",
                "Unicon Post Stitching MC",
                "Unrepaired",
                "UP-LIFT ",
                "UPPER AUTO PRIMER SPRAY FOR LCA PROJECT",
                "Upper Heater Setting",
                "Upper Steam Conditioner and Upper Dry Conveyor",
                "USM Cutting M/C",
                "USM CUTTING M/C",
                "UV CONVEYOR ",
                "UV Curing Equipment ",
                "UV Curing Equipment",
                "UV CURING EQUIPNENT M/C",
                "UV CURING EQUIPNENT M/C(SECONHAND)",
                "UV HEATING CONVEYER",
                "UV Primer Conveyor",
                "VERTICAL AUTO RACK",
                "VERTICAL AUTO RACK/KE CHUA HANG TU DONG",
                "Vertical Buffing and Dust Collector",
                "Vibration Selector M/C",
                "Water Base Adhesion Roller M/C",
                "WATER BASE ADHESION ROLLER M/C",
                "WATER BASE ADHESION TAPPING M/C",
                "WATER BASE LAMINATING M/C",
                "Water Base Roll Coater M/C",
                "Water Chiller",
                "WATER CHILLER (50RT)",
                "WATER CHILLER (5HP)",
                "WATER COOLED CHILLER SYSTEM",
                "WATER CURTAIN SPRAY CABINE M/C",
                "WIN WING ",
                "X-RAY INSPECTION M/C"
            ]),
            cost_dept_nm: faker.helpers.arrayElement([
                "Adidas Core - Dev",
                "CC1 - Cutting",
                "CC1 - Stitching",
                "CC2 - Stitching",
                "CKD Team",
                "CM EVA",
                "CTY CHEONG AM_101348",
                "CTY HOANG DINH HOAN",
                "CTY MOA VINA",
                "DS - Stitching",
                "F1 - Assembly",
                "F1 - Cutting",
                "F1 - Stitching",
                "F1 - Stockfitting",
                "F2 - Assembly",
                "F2 - Cutting",
                "F2 - Stitching",
                "F2 - Stockfitting",
                "F3 - Admin",
                "F3 - Assembly",
                "F3 - Cutting",
                "F3 - Stitching",
                "F3 - Stockfitting",
                "F5 - Admin",
                "F5 - Assembly",
                "F5 - Cutting",
                "F5 - Stitching",
                "F5 - Stockfitting",
                "IM EVA",
                "In-House",
                "Lecaf - Common",
                "LT - Stitching",
                "Maintenance",
                "Material",
                "Press - O/S",
                "Reebok - Dev",
                "RG - Cutting",
                "test1",
                "VT - Stitching"
            ]),
            lct_sts_nm: faker.helpers.arrayElement(['Export', 'Import']),
            sp_nm: faker.helpers.arrayElement([
                " ZHEJIANG CPO I & EXPORT CO.,LTD",
                "C.T.M. CO., LTD",
                "CHANG YIH AUTOMATIC SCREEN PRINTING",
                "CHENFENG MACHINERY AND ENTERPRICE C",
                "CHINA WORLDBEST GROUP CO.,LTD",
                "COMAY  INTL  HK  LIMITED",
                "COMELZ S.p.A",
                "CTY TNHH HS VUNG TAU",
                "CTY TNHH KD VIETNAM",
                "CTY TNHH MTV  DONG VUONG",
                "CTY TNHH MTV DAI VUONG",
                "CTY TNHH MTV-TMDV TRUNG PHAT",
                "CTY TNHH NAVITAS VIET NAM",
                "CTY TNHH TM HOANG DAT",
                "CTY TNHH TM&DV KIM THINH",
                "DA YU MACHINERY INDUSTRIAL CO., LTD",
                "DEA SUNG PRECISION AND IND.",
                "DNTN THUONG MAI THIEN NGUYEN",
                "DONGGUAN HONGYI IMP & EXP CO.,LTD",
                "DONGGUAN MACHINERY IMP & EXP CO.,LT",
                "FU TONG INTERNATIONAL LOGISTICS(HK)",
                "FUJIAN HUA MIN IMPORT AND EXPORT CO",
                "GD HANS YUEMING LASER TECH CO.,LTD",
                "GUANGDONG SHENGDA TECHNOLOGY",
                "HAN JIN INDUSTRIAL CO., LTD",
                "HS Corporation",
                "HWA SEUNG Networks Co.,Ltd",
                "HWANG SUN ENTERPRISE CO, LTD",
                "HWASEUNG INDUSTRIES CO.,LTD.",
                "JANG CHUN SHOE MANUFACTURING",
                "JIAMA MACHINE FACTORY",
                "KING STEEL INTERNATIONAL CO.,LTD",
                "KOREA TECHNO CO.,LTD",
                "KUKDONG MACHINERY CO.,LTD",
                "NEW SUNSHINE INDUSTRY COMPANY LIMIT",
                "PT.HANJIN INDONESIA JAVA",
                "Quanzhou Lianhua Industrial Co.,Ltd",
                "QUINGDAO KUKDONG MACHINERY CO.,LTD",
                "QUZHOU TAIWEI PRECISE MACHINERY CO.",
                "SHANGHAI ATOM CUTTING CO., LTD",
                "SHANGHAI EASEMENT ELECTRIC CO.,LTD",
                "SHANGHAI EAST BEST INTL BUSSINE DE",
                "SHANGHAI GUIYI EQUIPMENT CO.,LTD",
                "SUNSTAR CO.,LTD",
                "SUPER KERUI INTL HK LIMITED",
                "TEN SHEEG MACHINERY CO.,LTD",
                "WENZHOU N&A FOREIGN TRADE CO.,LTD.",
                "YANCHENG CITY HUASEN MACHINERY",
                "YE HONE ENTERPRISE CO.,LTD"
            ]),
            mgm_dept_nm: faker.helpers.arrayElement([
                "Adidas Core - Dev",
                "CC1 - Cutting",
                "CC1 - Stitching",
                "CC2 - Stitching",
                "CKD Team",
                "CM EVA",
                "CTY CHEONG AM_101348",
                "CTY HOANG DINH HOAN",
                "CTY MOA VINA",
                "DS - Stitching",
                "F1 - Assembly",
                "F1 - Cutting",
                "F1 - Stitching",
                "F1 - Stockfitting",
                "F2 - Assembly",
                "F2 - Cutting",
                "F2 - Stitching",
                "F2 - Stockfitting",
                "F3 - Admin",
                "F3 - Assembly",
                "F3 - Cutting",
                "F3 - Stitching",
                "F3 - Stockfitting",
                "F5 - Admin",
                "F5 - Assembly",
                "F5 - Cutting",
                "F5 - Stitching",
                "F5 - Stockfitting",
                "IM EVA",
                "In-House",
                "Lecaf - Common",
                "LT - Stitching",
                "Maintenance",
                "Material",
                "Press - O/S",
                "Reebok - Dev",
                "RG - Cutting",
                "test1",
                "VT - Stitching"
            ]),
            print_yn: faker.helpers.arrayElement(['Y', 'N']),
            use_yn: faker.helpers.arrayElement(['Y', 'N']),
            as_no: 700000 + i,
            as_sno: 800000 + i,
            srl_no: 900000 + i,
            re_mark: faker.commerce.productDescription(),
            dev_start_dt: startDate,
            puchs_dt: punchDate,
            vailed_dt: validDate,
        })
    }

    return equipments;
}

const MakeExcel = () => {
    const [row, setRow] = useState(50);

    const handleExportExcel = () => {

        const Heading = [['Corp', 'Storage', 'Manufacture', 'Model', 'Material', 'Material Name', 'Cost Dept',
            'Storage Status', 'Supplier', 'Management Dept', 'Print Y/N', 'Use Y/N', 'Asset Number', 'Asset Serial',
            'Serial Number', 'Re Mark', 'Start Date', 'Purchased Date', 'Valid Date'
        ]];
        const Data = makeEquipments(row);

        const wb = XLSX.utils.book_new();
        const ws = XLSX.utils.json_to_sheet([]);

        XLSX.utils.sheet_add_aoa(ws, Heading);
        XLSX.utils.sheet_add_json(ws, Data, {origin: 'A2', skipHeader: true});

        XLSX.utils.book_append_sheet(wb, ws, "Data");
        XLSX.writeFile(wb, "Equipment Example.xlsx");
    };

    return (
        <>
            <section className='w-full h-screen flex items-center justify-center'>
                <ButtonGroup className='max-w-sm'>
                    <Input value={row} onChange={(e) => setRow(Number(e.target.value))}/>
                    <Button onClick={handleExportExcel}>Export Excel</Button>
                </ButtonGroup>
            </section>

        </>
    );
}

export default MakeExcel;